### ISSUE TITLE
path+=("${0:h}/bin" "${path[@]}") should say path=( … )

### ISSUE THREAD

**Issue by psprint** [decayofmind/zsh-iterm2-utilities#1]
Hi.
The plugin at the same time appends to `$path` both with `+=` and by including `${path[@]}` in the assignment. It appears that only the second one is being needed.

The code from `iterm2-utils.plugin.zsh`:
```zsh
path+=("${0:h}/bin" "${path[@]}")
```

**Comment by decayofmind** [comment]
Hi @psprint, thanks for spotting this out. I've removed `${path[@]}` from the equation. Please, update the plugin.
